# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [NicoGrassetto]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# patreon: your-handle
# open_collective: your-collective
# liberapay: your-handle
# custom: ["https://example.com/donate"]
